### ISSUE TITLE
Zeus?

### ISSUE THREAD

**Issue by choyrim** [uber/RemoteShuffleService#25]
Is this project the same as the Uber Zeus project from the Spark AI Summit?

https://databricks.com/session_na20/zeus-ubers-highly-scalable-and-distributed-shuffle-as-a-service

I tried asking this in an email to remoteshuffleservice@googlegroups.com but it bounced.

**Comment by vectorijk** [comment]
yes, it is the same. zeus is the name we used.

it is a new created google group. probably, we don't have the correct setting :) now, I changed the policy. anyone can post in this group.

**Comment by choyrim** [comment]
thank you for the confirmation. great to hear that zeus is out now.

the google group doesn't show in a search

https://groups.google.com/search/groups?q=remoteshuffleservice
