### ISSUE TITLE
Compile error on Spark30 branch

### ISSUE THREAD

**Issue by HuiboPeng** [uber/RemoteShuffleService#31]
I try to compile Spark30 branch, but it compile error. The error info is as followed:
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.1.1:shade (default) on project remote-shuffle-service: Error creating shaded jar: Problem shading JAR /home/ec2-user/.m2/repository/org/glassfish/jersey/core/jersey-common/2.30/jersey-common-2.30.jar entry META-INF/versions/11/org/glassfish/jersey/internal/jsr166/SubmissionPublisher$1.class: java.lang.IllegalArgumentException -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`
Can anyone help to check this?

**Comment by hiboyang** [comment]
Are you using java 10 or java 11? maybe you could try adding exclusions like following to dependencies which use org.glassfish.jersey.core?

```
            <exclusions>
                <exclusion>
                    <groupId>org.glassfish.jersey.core</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>
```

You could use "mvn dependency:tree -X" to see what dependencies use org.glassfish.jersey.core
