### ISSUE TITLE
Does rss support hiveOnSpark?

### ISSUE THREAD

**Issue by jinzhejz** [uber/RemoteShuffleService#56]
Hi,

I wonder if rss support hiveOnSpark now.

If it is not supported, is there a schedule about it?

Thanks

**Comment by mayurdb** [comment]
Yes, it is supported. We internally run Hive on Sparl (HoS) 2.3.2 on RSS but haven't tried out on HoS 2.4.3 yet. Did you face any issues?

**Comment by jinzhejz** [comment]
not yet, I just want to confirm this. I will try it later :)

**Comment by jinzhejz** [comment]
Close this issue and thanks for the reply :)
