### ISSUE TITLE
Rss shuffle data size is much larger than external shuffle service

### ISSUE THREAD

**Issue by YutingWang98** [uber/RemoteShuffleService#90]
Hi team, 

I noticed that the RSS genereates almost 2 times more shuffle data than external shuffle service. For example, a job stage with rss has a shuffle write size of 720 TB, but external shuffle service only has 370 TB, and they are using the same inputs and codes. We also tried with some other job, and got the similar result.

We first suspect this may cause by no compression, but I took a look at the RssShuffleManager, and seems like there is compression/decompression on client side using LZ4(https://github.com/uber/RemoteShuffleService/blob/master/src/main/scala/org/apache/spark/shuffle/RssShuffleWriter.scala#L205, https://github.com/uber/RemoteShuffleService/blob/master/src/main/scala/org/apache/spark/shuffle/rss/BlockDownloaderPartitionRecordIterator.scala#L167).

Any ideas about possible causes of such a big margin of shuffle data? Thanks.

**Comment by hiboyang** [comment]
Hi @YutingWang98, this is interesting finding! For the size 720 TB/370 TB, is this disk file size, or the stats shown in Spark UI?

**Comment by YutingWang98** [comment]
Hi @hiboyang, thank you for the reply! It is the stats from spark UI stage tab ('Shuffle Write Size / Records' value). Also, I just did more tests on a same job and here are my findings: 

1. default settings 
   (rss using lz4, ess using zstd)
    - rss: 3.1 GiB
    - ess: 1927.1 MiB
2. disable compression 
   (removed rss compression and set 'spark.shuffle.compress=false' in ess)
   - rss: 5.7 GiB 
   - ess: 5.6 GiB
3. switch compression method
   (only tried on ess so far)
  - spark.io.compression.codec=zstd: 1927 MB
  - spark.io.compression.codec=lz4: 2.7 GB
  - spark.io.compression.codec=lzf: 2.7GB 
  - spark.io.compression.codec=snappy: 2.7 GB

So, I think it is worth trying to switch compression in Rss from lz4 to zstd, and see if the shuffle data size can decrease.

**Comment by hiboyang** [comment]
Nice to know zstd has better compression ratio. I created a PR to support zstd in RSS: https://github.com/uber/RemoteShuffleService/pull/91/files

**Comment by hiboyang** [comment]
No specific reason :) I changed it to level 1 in the PR, but forgot to reply the comment here.

**Comment by YutingWang98** [comment]
I saw your changes in the pull request! Thanks so much.
